title: My Custom Blog
description: A blog built completely from scratch
theme: []

# These lines are for custom repo names:
url: "https://nd-50424.github.io" #include your username
baseurl: "/a-mech-e-journal" #use exact repo name
