title: A Random Mech-E Student's Journal
description: A blog built with Github and Jekyll
theme: []

# These lines are for custom repo names:
url: "https://nd-50424.github.io" #include your username
baseurl: "/a-mech-e-journal" #use exact repo name
