title: A Random Mech-E Student's Journal
description: A blog built with Github and Jekyll
theme: []

# These lines are for custom repo names:
#include your username
url: "https://nd-50424.github.io" 
#use exact repo name
baseurl: "/a-mech-e-journal"
